### PR TITLE
Adding support for updated G3100 login mechanism

### PR DESCRIPTION
**Pull request by BrianWithAHat**
After a firmware update login started failing. This PR adds support for a newer login POST body format to support the 3.1.1.17 G3100 firmware.

This was only tested with the 3.1.1.17 firmware.

### CODE REVIEW

**Comment by cisasteelersfan** [comment]
Thanks!

**Comment by BrianWithAHat** [comment]
Thanks for the quick merge and publish to Pypi! Are you planning to submit a PR to home assistant for the version bump or would you like me to?

**Comment by cisasteelersfan** [comment]
Hi Brian, do you mind sending the PR to home assistant? Thanks!

**Comment by BrianWithAHat** [comment]
Created https://github.com/home-assistant/core/pull/74284 to propagate to HA.

**Pull request merged**
